### ISSUE TITLE
Custom arguments on tables

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-graphql#58]
Relates to #16. How about if you could define custom arguments on tables which worked something like this:
```graphql
trees(radius: {"lat": 37.78, "lng": -122.43, "km": 10}) {
  nodes {
    id
    name
  }
}
```
The `radius` here would be a custom argument defined in the plugin configuration.

Maybe it can be defined in terms of the `where` SQL clauses it adds?

**Comment by simonw** [comment]
Syntax something like:
```yaml
plugins:
  datasette-graph-ql:
    databases:
      sf-trees:
        tables:
          arguments:
            radius:
              inputs:
                lat: float
                lng: float
                km: float
              where_sql: |-
                PtDistWithin(geometry, MakePoint(:lat ,:lng, 4326), :km * 1000)=TRUE
```
