### ISSUE TITLE
Doesn't work with authenticated Datasette instances

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-graphql#97]
The GraphQL explorer at least doesn't - you get this error:

<img width="732" alt="CleanShot 2023-09-07 at 10 07 27@2x" src="https://github.com/simonw/datasette-graphql/assets/9599/29eaab47-9832-4d5b-a7fb-b207ffb308a3">

Interesting that the API introspection DOES work, but the actual query execution does not.

**Comment by simonw** [comment]
I set that instance up with https://datasette.io/datasette-auth-tokens and this config:
```yaml
plugins:
  datasette-auth-tokens:
    tokens:
    - token: secret-token
      actor:
        id: bot

allow:
  id:
  - bot
  - root
```
